Repository azimutlabs/rollup, pull requests merged in 2021-02, with the labels that each got.

#24 refactor(rollup-config)!: change compose, combine and finalize function signatures (#22)
  packages/rollup-config/src/RollupConfig.ts
  packages/rollup-config/src/services/combine.ts
  packages/rollup-config/src/services/compose.ts
  packages/rollup-config/src/types/RollupConfigFinalizeOptions.ts
Labels: enhancement

#25 fix(rollup-config): remove All option from current environment
  packages/rollup-config/src/services/getCurrentEnv.ts
Labels: bug

#27 docs: add contributing (#9)
  CONTRIBUTING.md
Labels: documentation

#30 build: add rollup-config as a peer dependency to all config packages (#26)
  .pnp.js
  packages/rollup-config-babel/package.json
  packages/rollup-config-essentials/package.json
  packages/rollup-config-typescript/package.json
  yarn.lock
Labels: enhancement

#28 docs: update readme (#10)
  README.md
Labels: documentation

#32 docs(rollup-plugin-external): add readme (#31)
  packages/rollup-plugin-external/README.md
Labels: documentation
