Repository azimutlabs/rollup, pull requests merged in 2021-03, with the labels that each got.

#39 feat(rollup-config-essentials): add @rollup/plugin-alias to support absolute imports (#34)
  .pnp.js
  .yarn/cache/@rollup-plugin-alias-npm-3.1.2-10d0b877c3-cb0e59b253.zip
  packages/rollup-config-essentials/package.json
  packages/rollup-config-essentials/src/config.ts
  packages/rollup-config-essentials/src/types/RollupConfigEssentialsPlugins.ts
  yarn.lock
Labels: enhancement

#42 docs(rollup): update readme
  packages/rollup/README.md
Labels: documentation

#44 refactor(rollup): rename useWorkspaces to fromWorkspaces (#43)
  .pnp.js
  .yarn/cache/@azimutlabs-rollup-file-4c76e5d5ac-4100c3946d.zip
  .yarn/cache/@azimutlabs-rollup-file-a01eb0858e-7d1b2f75f3.zip
  packages/rollup/src/collect.ts
  packages/rollup/src/fromWorkspaces.ts
  packages/rollup/src/index.ts
  packages/rollup/src/useWorkspaces.ts
  packages/tests/src/rollup/packages/c/rollup.config.js
  packages/tests/src/rollup/rollup.test.ts
  yarn.lock
Labels: bug

#49 fix(rollup-config-babel): add root field as rootDir (#46)
  packages/rollup-config-babel/package.json
  packages/rollup-config-babel/src/config.ts
Labels: bug
